// Code generated by sqlc. DO NOT EDIT.

package filesdb

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

type FileStatus string

const (
	FileStatusCreated  FileStatus = "created"
	FileStatusUploaded FileStatus = "uploaded"
)

func (e *FileStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileStatus(s)
	case string:
		*e = FileStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FileStatus: %T", src)
	}
	return nil
}

type File struct {
	ID        int32      `json:"id"`
	Status    FileStatus `json:"status"`
	FileID    uuid.UUID  `json:"file_id"`
	FileName  string     `json:"file_name"`
	Downloads int64      `json:"downloads"`
	CreatedAt time.Time  `json:"created_at"`
}
